spring.application.name=taskManagSys
  # ========================
  # НАСТРОЙКИ БАЗЫ ДАННЫХ
  # ========================
  
  # URL подключения (обрати внимание на порт 5431!)
spring.datasource.url=jdbc:postgresql://localhost:5431/task_management
spring.datasource.username=postgres
spring.datasource.password=postgres
  
  # ========================
  # НАСТРОЙКИ JPA/HIBERNATE
  # ========================
  
  # Автоматически создавай таблицы на основе Entity-классов
spring.jpa.hibernate.ddl-auto=update
  
  # Показывай SQL-запросы в консоли (ОЧЕНЬ полезно для отладки!)
spring.jpa.show-sql=true
  
  # Красиво форматируй SQL
spring.jpa.properties.hibernate.format_sql=true
  
  # Диалект PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
