spring.application.name=taskManagSys
  # ========================
  # ????????? ???? ??????
  # ========================
  
  # URL ??????????? (?????? ???????? ?? ???? 5431!)
spring.datasource.url=jdbc:postgresql://localhost:5432/task_management
spring.datasource.username=postgres
spring.datasource.password=postgres
  
  # ========================
  # ????????? JPA/HIBERNATE
  # ========================
  
  # ????????????? ???????? ??????? ?? ?????? Entity-???????
spring.jpa.hibernate.ddl-auto=update
  
  # ????????? SQL-??????? ? ??????? (????? ??????? ??? ???????!)
spring.jpa.show-sql=true
  
  # ??????? ?????????? SQL
spring.jpa.properties.hibernate.format_sql=true
  
  # ??????? PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
