server.port=8081
spring.application.name=taskManagSys

# Database
spring.datasource.url=jdbc:postgresql://localhost:5434/task_management
spring.datasource.username=astalavista
spring.datasource.password=13ReasonsWhy
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Logging
logging.level.ru.astalavista.taskManagSys=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# Validation
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# Telegram Bot Configuration
telegram.bot.enabled=true
telegram.bot.username=astalavista_task_bot
telegram.bot.token=8554618987:AAFuB8hIp86p8X4sk_VEtXhibBCB4LbQYvI
telegram.bot.admin-id=1063046326

# Bot Settings
telegram.bot.notifications.enabled=true
telegram.bot.daily-report-time=09:00
telegram.bot.check-overdue-interval=30